services:
  lastfm-rpc:
    build: .
    container_name: discord-lastfm-rpc
    restart: unless-stopped
    env_file: .env
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
